# Generated by Django 2.2.5 on 2019-11-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20191105_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(help_text='How mant people will be staying?'),
        ),
    ]
